name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config # Checks for syntax errors in your YAML

      - name: Test Infrastructure
        run: |
          docker compose up -d
          sleep 15
          docker compose ps # Checks if all containers are 'running'

  build-and-push:
    needs: test # Only runs if 'test' job finishes successfully
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/week3:latest

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/week3/templates:latest
